### ISSUE TITLE
java.lang.NullPointerException: Ticking entity

### ISSUE THREAD

**Issue by Laotouy** [DThaiPome/Pixelmon-9.1.9-Patches#1]
---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 24-1-6 下午10:59
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at com.pixelmonmod.pixelmon.entities.pokeballs.OccupiedPokeBallEntity.handler$zzf000$onHit(OccupiedPokeBallEntity.java:731) ~[pixelmon:1.16.5-9.1.9] {re:mixin,re:classloading,pl:mixin:APP:newversionpatches.mixin.json:OccupiedPokeBallEntityMixin,pl:mixin:A}
	at com.pixelmonmod.pixelmon.entities.pokeballs.OccupiedPokeBallEntity.func_70227_a(OccupiedPokeBallEntity.java) ~[pixelmon:1.16.5-9.1.9] {re:mixin,re:classloading,pl:mixin:APP:newversionpatches.mixin.json:OccupiedPokeBallEntityMixin,pl:mixin:A}
	at net.minecraft.entity.projectile.ProjectileEntity.preOnHit(ProjectileEntity.java:122) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.entity.projectile.ThrowableEntity.func_70071_h_(ThrowableEntity.java:67) ~[?:?] {re:classloading,pl:runtimedistcleaner:A,re:mixin,pl:runtimedistcleaner:A}
	at com.pixelmonmod.pixelmon.entities.pokeballs.PokeBallEntity.func_70071_h_(PokeBallEntity.java:227) ~[pixelmon:1.16.5-9.1.9] {re:classloading,pl:runtimedistcleaner:A,re:mixin,pl:runtimedistcleaner:A}
	at com.pixelmonmod.pixelmon.entities.pokeballs.OccupiedPokeBallEntity.func_70071_h_(OccupiedPokeBallEntity.java:132) ~[pixelmon:1.16.5-9.1.9] {re:mixin,re:classloading,pl:mixin:APP:newversionpatches.mixin.json:OccupiedPokeBallEntityMixin,pl:mixin:A}
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:756) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:containerminecartentityloopfix.mixins.json:ServerWorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.world.World.func_217390_a(World.java:811) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:529) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:containerminecartentityloopfix.mixins.json:ServerWorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1049) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:336) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:943) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:775) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:265) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_301] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.pixelmonmod.pixelmon.entities.pokeballs.OccupiedPokeBallEntity.handler$zzf000$onHit(OccupiedPokeBallEntity.java:731) ~[pixelmon:1.16.5-9.1.9] {re:mixin,re:classloading,pl:mixin:APP:newversionpatches.mixin.json:OccupiedPokeBallEntityMixin,pl:mixin:A}
	at com.pixelmonmod.pixelmon.entities.pokeballs.OccupiedPokeBallEntity.func_70227_a(OccupiedPokeBallEntity.java) ~[pixelmon:1.16.5-9.1.9] {re:mixin,re:classloading,pl:mixin:APP:newversionpatches.mixin.json:OccupiedPokeBallEntityMixin,pl:mixin:A}
	at net.minecraft.entity.projectile.ProjectileEntity.preOnHit(ProjectileEntity.java:122) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.entity.projectile.ThrowableEntity.func_70071_h_(ThrowableEntity.java:67) ~[?:?] {re:classloading,pl:runtimedistcleaner:A,re:mixin,pl:runtimedistcleaner:A}
	at com.pixelmonmod.pixelmon.entities.pokeballs.PokeBallEntity.func_70071_h_(PokeBallEntity.java:227) ~[pixelmon:1.16.5-9.1.9] {re:classloading,pl:runtimedistcleaner:A,re:mixin,pl:runtimedistcleaner:A}
	at com.pixelmonmod.pixelmon.entities.pokeballs.OccupiedPokeBallEntity.func_70071_h_(OccupiedPokeBallEntity.java:132) ~[pixelmon:1.16.5-9.1.9] {re:mixin,re:classloading,pl:mixin:APP:newversionpatches.mixin.json:OccupiedPokeBallEntityMixin,pl:mixin:A}
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:756) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:containerminecartentityloopfix.mixins.json:ServerWorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
-- Entity being ticked --

**Comment by DThaiPome** [comment]
This is related to a fix I included in this mod for a crash related to throwing pokeballs. Looks like the original issue was fixed in Pixelmon v9.1.10.

Thanks for the log :)

Edit: I see that this log is from Pixelmon 9.1.9. I see the issue and can fix the crash. Thanks again and sorry for the inconvenience.

**Comment by DThaiPome** [comment]
See the latest release: https://github.com/DThaiPome/Pixelmon-9.1.9-Patches/releases/tag/9.1.9.1.9
